name: trigger_env
dependencies:
  # Requirements for fit plotting
  - python=3.7
  - pip>=21.0.1
  - conda-forge::xrootd
  - conda-forge::root=6.20.04  # specific version to ensure plots made with ROOT look good
  - llvmlite>=0.34
  - numpy
  - keras
  - tensorflow
  - pytorch
  - seaborn
  - matplotlib
  - pip:
    - uproot==3.11.3 
    - atsge>0.1.11
    - numba!=0.47.0
    - awkward==0.12.21
    - dask==2021.5.1
    - dask-jobqueue==0.7.2
  - plotly::plotly>4.14.0
  - plotly::plotly-orca>1.3.0
